### PR TITLE
Notebook Downloads (Standard Library Changes)

### PR DESCRIPTION
**Pull request by jashkenas**
* Creates UMD and ES Module bundles of the standard library.

### CODE REVIEW

**Comment by jashkenas** [comment]
@mbostock — if approved, I'd like to merge and publish this PR as version 1.0.0 on npm...

**Comment by mbostock** [comment]
Per https://github.com/tc39/proposal-observable, `Observable` may be a thing in ECMAScript in the future, although it is just stage 1. I suppose we could use `observablehq` as the namespace?

**Comment by mbostock** [comment]
My other concern #31 #32 is whether we should formally deprecate (though still support) the following methods:

* Generators.filter
* Generators.map
* DOM.element
* DOM.input
* DOM.range
* DOM.select
* DOM.text

That said I’d probably *not* deprecate:

* DOM.canvas
* DOM.svg

I find myself still using DOM.svg a lot because it sets the viewBox automatically, likewise DOM.context2d is useful for its automatic high DPI support, and might as well keep DOM.canvas for symmetry with DOM.svg and for WebGL.

In practice this would mean moving the documentation for the deprecated methods from README.md to a DEPRECATED.md, and perhaps adding these to the deprecated list for autocomplete.

**Comment by jashkenas** [comment]
CSS and UMD namespaces updated across the board to `observablehq`. 

(Although, I still hold out hope that one day we'll be able to purchase observable.com)...

Just for expediency's sake: If we're not changing any of the functionality (yet), just the documentation, I don't think we need to make a decision on the deprecations before merging this branch and publishing a 1.0.0 — as long as the functionality remains in place, we can deprecate at any point afterwards.

**Comment by mbostock** [comment]
Okay, that’s fair; we can punt on deprecation. 👍

**Pull request merged**
